#ifndef JEDEC_HPP_
#define JEDEC_HPP_

#include <unordered_map>
#include <string>
#include <sstream>

/* PDF downloaded for free from https://www.jedec.org/system/files/docs/JEP106BG.pdf */
/* The present list is complete as of May 1, 2023. */

#define CONTINUATION_CODE                   "7F"

std::unordered_map<std::string, std::string> bank1 {
    { "01", "AMD" },
    { "02", "AMI" },
    { "83", "Fairchild" },
    { "04", "Fujitsu" },
    { "85", "GTE" },
    { "86", "Harris" },
    { "07", "Hitachi" },
    { "08", "Inmos" },
    { "89", "Intel" },
    { "8A", "I.T.T" },
    { "0B", "Intersil" },
    { "8C", "Monolithic Memories" },
    { "0D", "Mostek" },
    { "0E", "Freescale (Motorola)" },
    { "8F", "National" },
    { "10", "NEC" },
    { "91", "RCA" },
    { "92", "Raytheon" },
    { "13", "Conexant (Rockwell)" },
    { "94", "Seeq" },
    { "16", "Synertek" },
    { "97", "Texas Instruments" },
    { "98", "Kioxia Corporation" },
    { "19", "Xicor" },
    { "1A", "Zilog" },
    { "9B", "Eurotechnique" },
    { "1C", "Mitsubishi" },
    { "9D", "Lucent (AT&T)" },
    { "9E", "Exel" },
    { "1F", "Atmel" },
    { "20", "STMicroelectronics" },
    { "A1", "Lattice Semi" },
    { "A2", "NCR" },
    { "23", "Wafer Scale Integration" },
    { "A4", "IBM" },
    { "25", "Tristar" },
    { "26", "Visic" },
    { "A7", "Intl. CMOS Technology" },
    { "A8", "SSSI" },
    { "29", "Microchip Technology" },
    { "2A", "Ricoh Ltd" },
    { "AB", "VLSI" },
    { "2C", "Micron Technology" },
    { "AD", "SK Hynix" },
    { "AE", "OKI Semiconductor" },
    { "2F", "ACTEL" },
    { "B0", "Sharp" },
    { "31", "Catalyst" },
    { "32", "Panasonic" },
    { "B3", "IDT" },
    { "34", "Cypress" },
    { "B5", "DEC" },
    { "B6", "LSI Logic" },
    { "37", "Zarlink (Plessey)" },
    { "38", "UTMC" },
    { "B9", "Thinking Machine" },
    { "BA", "Thomson CSF" },
    { "3B", "Integrated CMOS (Vertex)" },
    { "BC", "Honeywell" },
    { "3D", "Tektronix" },
    { "3E", "Oracle Corporation" },
    { "BF", "Silicon Storage Technology" },
    { "40", "ProMos/Mosel Vitelic" },
    { "C1", "Infineon (Siemens)" },
    { "C2", "Macronix" },
    { "43", "Xerox" },
    { "C4", "Plus Logic" },
    { "45", "Western Digital Technologies Inc" },
    { "46", "Elan Circuit Tech" },
    { "C7", "European Silicon Str." },
    { "C8", "Apple Computer" },
    { "49", "Xilinx" },
    { "4A", "Compaq" },
    { "CB", "Protocol Engines" },
    { "4C", "SCI" },
    { "CD", "ABLIC" },
    { "CE", "Samsung" },
    { "4F", "I3 Design System" },
    { "D0", "Klic" },
    { "51", "Crosspoint Solutions" },
    { "52", "Alliance Memory Inc" },
    { "D3", "Tandem" },
    { "54", "Hewlett-Packard" },
    { "D5", "Integrated Silicon Solutions" },
    { "D6", "Brooktree" },
    { "57", "New Media" },
    { "58", "MHS Electronic" },
    { "D9", "Performance Semi" },
    { "DA", "Winbond Electronic" },
    { "5B", "Kawasaki Steel" },
    { "DC", "Bright Micro" },
    { "5D", "TECMAR" },
    { "5E", "Exar" },
    { "DF", "PCMCIA" },
    { "E0", "LG Semi (Goldstar)" },
    { "61", "Northern Telecom" },
    { "62", "Sanyo" },
    { "E3", "Array Microsystems" },
    { "64", "Crystal Semiconductor" },
    { "E5", "Analog Devices" },
    { "E6", "PMC-Sierra" },
    { "67", "Asparix" },
    { "68", "Convex Computer" },
    { "E9", "Quality Semiconductor" },
    { "EA", "Nimbus Technology" },
    { "6B", "Transwitch" },
    { "EC", "Micronas (ITT Intermetall)" },
    { "6D", "Cannon" },
    { "6E", "Altera" },
    { "EF", "NEXCOM" },
    { "70", "Qualcomm" },
    { "F1", "Sony" },
    { "F2", "Cray Research" },
    { "73", "AMS(Austria Micro)" },
    { "F4", "Vitesse" },
    { "75", "Aster Electronics" },
    { "76", "Bay Networks (Synoptic)" },
    { "F7", "Zentrum/ZMD" },
    { "F8", "TRW" },
    { "79", "Thesys" },
    { "7A", "Solbourne Computer" },
    { "FB", "Allied-Signal" },
    { "7C", "Dialog Semiconductor" },
    { "FD", "Media Vision" },
    { "FE", "Numonyx Corporation" }
};

// Continuation 1
std::unordered_map<std::string, std::string> bank2 {
    { "01", "Cirrus Logic" },
    { "02", "National Instruments" },
    { "83", "ILC Data Device" },
    { "04", "Alcatel Mietec" },
    { "85", "Micro Linear" },
    { "86", "Univ. of NC" },
    { "07", "JTAG Technologies" },
    { "08", "BAE Systems (Loral)" },
    { "89", "Nchip" },
    { "8A", "Galileo Tech" },
    { "0B", "Bestlink Systems" },
    { "8C", "Graychip" },
    { "0D", "GENNUM" },
    { "0E", "Imagination Technologies Limited" },
    { "8F", "Robert Bosch" },
    { "10", "Chip Express" },
    { "91", "DATARAM" },
    { "92", "United Microelectronics Corp" },
    { "13", "TCSI" },
    { "94", "Smart Modular" },
    { "15", "Hughes Aircraft" },
    { "16", "Lanstar Semiconductor" },
    { "97", "Qlogic" },
    { "98", "Kingston" },
    { "19", "Music Semi" },
    { "1A", "Ericsson Components" },
    { "9B", "SpaSE" },
    { "1C", "Eon Silicon Devices" },
    { "9D", "Integrated Silicon Solution (ISSI)" },
    { "9E", "DoD" },
    { "1F", "Integ. Memories Tech." },
    { "20", "Corollary Inc" },
    { "A1", "Dallas Semiconductor" },
    { "A2", "Omnivision" },
    { "23", "EIV(Switzerland)" },
    { "A4", "Novatel Wireless" },
    { "25", "Zarlink (Mitel)" },
    { "26", "Clearpoint" },
    { "A7", "Cabletron" },
    { "A8", "STEC (Silicon Tech)" },
    { "29", "Vanguard" },
    { "2A", "Hagiwara Sys-Com" },
    { "AB", "Vantis" },
    { "2C", "Celestica" },
    { "AD", "Century" },
    { "AE", "Hal Computers" },
    { "2F", "Rohm Company Ltd" },
    { "B0", "Juniper Networks" },
    { "31", "Libit Signal Processing" },
    { "32", "Mushkin Enhanced Memory" },
    { "B3", "Tundra Semiconductor" },
    { "34", "Adaptec Inc" },
    { "B5", "LightSpeed Semi." },
    { "B6", "ZSP Corp" },
    { "37", "AMIC Technology" },
    { "38", "Adobe Systems" },
    { "B9", "Dynachip" },
    { "BA", "PNY Technologies Inc" },
    { "3B", "Newport Digital" },
    { "BC", "MMC Networks" },
    { "3D", "T Square" },
    { "3E", "Seiko Epson" },
    { "BF", "Broadcom" },
    { "40", "Viking Components" },
    { "C1", "V3 Semiconductor" },
    { "C2", "Flextronics (Orbit Semiconductor)" },
    { "43", "Suwa Electronics" },
    { "C4", "Transmeta" },
    { "45", "Micron CMS" },
    { "46", "American Computer & Digital Components Inc" },
    { "C7", "Enhance 3000 Inc" },
    { "C8", "Tower Semiconductor" },
    { "49", "CPU Design" },
    { "4A", "Price Point" },
    { "CB", "Maxim Integrated Product" },
    { "4C", "Tellabs" },
    { "CD", "Centaur Technology" },
    { "CE", "Unigen Corporation" },
    { "4F", "Transcend Information" },
    { "D0", "Memory Card Technology" },
    { "51", "CKD Corporation Ltd" },
    { "52", "Capital Instruments Inc" },
    { "D3", "Aica Kogyo Ltd" },
    { "54", "Linvex Technology" },
    { "D5", "MSC Vertriebs GmbH" },
    { "D6", "AKM Company Ltd" },
    { "57", "Dynamem Inc" },
    { "58", "NERA ASA" },
    { "D9", "GSI Technology" },
    { "DA", "Dane-Elec (C Memory)" },
    { "5B", "Acorn Computers" },
    { "DC", "Lara Technology" },
    { "5D", "Oak Technology Inc" },
    { "5E", "Itec Memory" },
    { "DF", "Tanisys Technology" },
    { "E0", "Truevision" },
    { "61", "Wintec Industries" },
    { "62", "Super PC Memory" },
    { "E3", "MGV Memory" },
    { "64", "Galvantech" },
    { "E5", "Gadzoox Networks" },
    { "E6", "Multi Dimensional Cons." },
    { "67", "GateField" },
    { "68", "Integrated Memory System" },
    { "E9", "Triscend" },
    { "EA", "XaQti" },
    { "6B", "Goldenram" },
    { "EC", "Clear Logic" },
    { "6D", "Cimaron Communications" },
    { "6E", "Nippon Steel Semi. Corp" },
    { "EF", "Advantage Memory" },
    { "70", "AMCC" },
    { "F1", "LeCroy" },
    { "F2", "Yamaha Corporation" },
    { "73", "Digital Microwave" },
    { "F4", "NetLogic Microsystems" },
    { "75", "MIMOS Semiconductor" },
    { "76", "Advanced Fibre" },
    { "F7", "BF Goodrich Data." },
    { "F8", "Epigram" },
    { "79", "Acbel Polytech Inc" },
    { "7A", "Apacer Technology" },
    { "FB", "Admor Memory" },
    { "7C", "FOXCONN" },
    { "FD", "Quadratics Superconductor" },
    { "FE", "3COM"  }
};

// Continuation 2
std::unordered_map<std::string, std::string> bank3 {
    { "01", "Camintonn Corporation" },
    { "02", "ISOA Incorporated" },
    { "83", "Agate Semiconductor" },
    { "04", "ADMtek Incorporated" },
    { "85", "HYPERTEC" },
    { "86", "Adhoc Technologies" },
    { "07", "MOSAID Technologies" },
    { "08", "Ardent Technologies" },
    { "89", "Switchcore" },
    { "8A", "Cisco Systems Inc" },
    { "0B", "Allayer Technologies" },
    { "8C", "WorkX AG (Wichman)" },
    { "0D", "Oasis Semiconductor" },
    { "0E", "Novanet Semiconductor" },
    { "8F", "E-M Solutions" },
    { "10", "Power General" },
    { "91", "Advanced Hardware Arch." },
    { "92", "Inova Semiconductors GmbH" },
    { "13", "Telocity" },
    { "94", "Delkin Devices" },
    { "15", "Symagery Microsystems" },
    { "16", "C-Port Corporation" },
    { "97", "SiberCore Technologies" },
    { "98", "Southland Microsystems" },
    { "19", "Malleable Technologies" },
    { "1A", "Kendin Communications" },
    { "9B", "Great Technology Microcomputer" },
    { "1C", "Sanmina Corporation" },
    { "9D", "HADCO Corporation" },
    { "9E", "Corsair" },
    { "1F", "Actrans System Inc" },
    { "20", "ALPHA Technologies" },
    { "A1", "Silicon Laboratories Inc (Cygnal)" },
    { "A2", "Artesyn Technologies" },
    { "23", "Align Manufacturing" },
    { "A4", "Peregrine Semiconductor" },
    { "25", "Chameleon Systems" },
    { "26", "Aplus Flash Technology" },
    { "A7", "MIPS Technologies" },
    { "A8", "Chrysalis ITS" },
    { "29", "ADTEC Corporation" },
    { "2A", "Kentron Technologies" },
    { "AB", "Win Technologies" },
    { "2C", "Tezzaron Semiconductor" },
    { "AD", "Extreme Packet Devices" },
    { "AE", "RF Micro Devices" },
    { "2F", "Siemens AG" },
    { "B0", "Sarnoff Corporation" },
    { "31", "Itautec SA" },
    { "32", "Radiata Inc" },
    { "B3", "Benchmark Elect. (AVEX)" },
    { "34", "Legend" },
    { "B5", "SpecTek Incorporated" },
    { "B6", "Hi/fn" },
    { "37", "Enikia Incorporated" },
    { "38", "SwitchOn Networks" },
    { "B9", "AANetcom Incorporated" },
    { "BA", "Micro Memory Bank" },
    { "3B", "ESS Technology" },
    { "BC", "Virata Corporation" },
    { "3D", "Excess Bandwidth" },
    { "3E", "West Bay Semiconductor" },
    { "BF", "DSP Group" },
    { "40", "Newport Communications" },
    { "C1", "Chip2Chip Incorporated" },
    { "C2", "Phobos Corporation" },
    { "43", "Intellitech Corporation" },
    { "C4", "Nordic VLSI ASA" },
    { "45", "Ishoni Networks" },
    { "46", "Silicon Spice" },
    { "C7", "Alchemy Semiconductor" },
    { "C8", "Agilent Technologies" },
    { "49", "Centillium Communications" },
    { "4A", "W.L. Gore" },
    { "CB", "HanBit Electronics" },
    { "4C", "GlobeSpan" },
    { "CD", "Element 14" },
    { "CE", "Pycon" },
    { "4F", "Saifun Semiconductors" },
    { "D0", "Sibyte Incorporated" },
    { "51", "MetaLink Technologies" },
    { "52", "Feiya Technology" },
    { "D3", "I & C Technology" },
    { "54", "Shikatronics" },
    { "D5", "Elektrobit" },
    { "D6", "Megic" },
    { "57", "Com-Tier" },
    { "58", "Malaysia Micro Solutions" },
    { "D9", "Hyperchip" },
    { "DA", "Gemstone Communications" },
    { "5B", "Anadigm (Anadyne)" },
    { "DC", "3ParData" },
    { "5D", "Mellanox Technologies" },
    { "5E", "Tenx Technologies" },
    { "DF", "Helix AG" },
    { "E0", "Domosys" },
    { "61", "Skyup Technology" },
    { "62", "HiNT Corporation" },
    { "E3", "Chiaro" },
    { "64", "MDT Technologies GmbH" },
    { "E5", "Exbit Technology A/S" },
    { "E6", "Integrated Technology Express" },
    { "67", "AVED Memory" },
    { "68", "Legerity" },
    { "E9", "Jasmine Networks" },
    { "EA", "Caspian Networks" },
    { "6B", "nCUBE" },
    { "EC", "Silicon Access Networks" },
    { "6D", "FDK Corporation" },
    { "6E", "High Bandwidth Access" },
    { "EF", "MultiLink Technology" },
    { "70", "BRECIS" },
    { "F1", "World Wide Packets" },
    { "F2", "APW" },
    { "73", "Chicory Systems" },
    { "F4", "Xstream Logic" },
    { "75", "Fast-Chip" },
    { "76", "Zucotto Wireless" },
    { "F7", "Realchip" },
    { "F8", "Galaxy Power" },
    { "79", "eSilicon" },
    { "7A", "Morphics Technology" },
    { "FB", "Accelerant Networks" },
    { "7C", "Silicon Wave" },
    { "FD", "SandCraft" },
    { "FE", "Elpida" }
};

// Continuation 3
std::unordered_map<std::string, std::string> bank4 {
    { "01", "Solectron" },
    { "02", "Optosys Technologies" },
    { "83", "Buffalo (Formerly Melco)" },
    { "04", "TriMedia Technologies" },
    { "85", "Cyan Technologies" },
    { "86", "Global Locate" },
    { "07", "Optillion" },
    { "08", "Terago Communications" },
    { "89", "Ikanos Communications" },
    { "8A", "Princeton Technology" },
    { "0B", "Nanya Technology" },
    { "8C", "Elite Flash Storage" },
    { "0D", "Mysticom" },
    { "0E", "LightSand Communications" },
    { "8F", "ATI Technologies" },
    { "10", "Agere Systems" },
    { "91", "NeoMagic" },
    { "92", "AuroraNetics" },
    { "13", "Golden Empire" },
    { "94", "Mushkin" },
    { "15", "Tioga Technologies" },
    { "16", "Netlist" },
    { "97", "TeraLogic" },
    { "98", "Cicada Semiconductor" },
    { "19", "Centon Electronics" },
    { "1A", "Tyco Electronics" },
    { "9B", "Magis Works" },
    { "1C", "Zettacom" },
    { "9D", "Cogency Semiconductor" },
    { "9E", "Chipcon AS" },
    { "1F", "Aspex Technology" },
    { "20", "F5 Networks" },
    { "A1", "Programmable Silicon Solutions" },
    { "A2", "ChipWrights" },
    { "23", "Acorn Networks" },
    { "A4", "Quicklogic" },
    { "25", "Kingmax Semiconductor" },
    { "26", "BOPS" },
    { "A7", "Flasys" },
    { "A8", "BitBlitz Communications" },
    { "29", "eMemory Technology" },
    { "2A", "Procket Networks" },
    { "AB", "Purple Ray" },
    { "2C", "Trebia Networks" },
    { "AD", "Delta Electronics" },
    { "AE", "Onex Communications" },
    { "2F", "Ample Communications" },
    { "B0", "Memory Experts Intl" },
    { "31", "Astute Networks" },
    { "32", "Azanda Network Devices" },
    { "B3", "Dibcom" },
    { "34", "Tekmos" },
    { "B5", "API NetWorks" },
    { "B6", "Bay Microsystems" },
    { "37", "Firecron Ltd" },
    { "38", "Resonext Communications" },
    { "B9", "Tachys Technologies" },
    { "BA", "Equator Technology" },
    { "3B", "Concept Computer" },
    { "BC", "SILCOM" },
    { "3D", "3Dlabs" },
    { "3E", "c’t Magazine" },
    { "BF", "Sanera Systems" },
    { "40", "Silicon Packets" },
    { "C1", "Viasystems Group" },
    { "C2", "Simtek" },
    { "43", "Semicon Devices Singapore" },
    { "C4", "Satron Handelsges" },
    { "45", "Improv Systems" },
    { "46", "INDUSYS GmbH" },
    { "C7", "Corrent" },
    { "C8", "Infrant Technologies" },
    { "49", "Ritek Corp" },
    { "4A", "empowerTel Networks" },
    { "CB", "Hypertec" },
    { "4C", "Cavium Networks" },
    { "CD", "PLX Technology" },
    { "CE", "Massana Design" },
    { "4F", "Intrinsity" },
    { "D0", "Valence Semiconductor" },
    { "51", "Terawave Communications" },
    { "52", "IceFyre Semiconductor" },
    { "D3", "Primarion" },
    { "54", "Picochip Designs Ltd" },
    { "D5", "Silverback Systems" },
    { "D6", "Jade Star Technologies" },
    { "57", "Pijnenburg Securealink" },
    { "58", "takeMS - Ultron AG" },
    { "D9", "Cambridge Silicon Radio" },
    { "DA", "Swissbit" },
    { "5B", "Nazomi Communications" },
    { "DC", "eWave System" },
    { "5D", "Rockwell Collins" },
    { "5E", "Picocel Co Ltd (Paion)" },
    { "DF", "Alphamosaic Ltd" },
    { "E0", "Sandburst" },
    { "61", "SiCon Video" },
    { "62", "NanoAmp Solutions" },
    { "E3", "Ericsson Technology" },
    { "64", "PrairieComm" },
    { "E5", "Mitac International" },
    { "E6", "Layer N Networks" },
    { "67", "MtekVision (Atsana)" },
    { "68", "Allegro Networks" },
    { "E9", "Marvell Semiconductors" },
    { "EA", "Netergy Microelectronic" },
    { "6B", "NVIDIA" },
    { "EC", "Internet Machines" },
    { "6D", "Memorysolution GmbH" },
    { "6E", "Litchfield Communication" },
    { "EF", "Accton Technology" },
    { "70", "Teradiant Networks" },
    { "F1", "Scaleo Chip" },
    { "F2", "Cortina Systems" },
    { "73", "RAM Components" },
    { "F4", "Raqia Networks" },
    { "75", "ClearSpeed" },
    { "76", "Matsushita Battery" },
    { "F7", "Xelerated" },
    { "F8", "SimpleTech" },
    { "79", "Utron Technology" },
    { "7A", "Astec International" },
    { "FB", "AVM gmbH" },
    { "7C", "Redux Communications" },
    { "FD", "Dot Hill Systems" },
    { "FE", "TeraChip" },
};

// Continuation 4
std::unordered_map<std::string, std::string> bank5 {
    { "01", "T-RAM Incorporated" },
    { "02", "Innovics Wireless" },
    { "83", "Teknovus" },
    { "04", "KeyEye Communications" },
    { "85", "Runcom Technologies" },
    { "86", "RedSwitch" },
    { "07", "Dotcast" },
    { "08", "Silicon Mountain Memory" },
    { "89", "Signia Technologies" },
    { "8A", "Pixim" },
    { "0B", "Galazar Networks" },
    { "8C", "White Electronic Designs" },
    { "0D", "Patriot Scientific" },
    { "0E", "Neoaxiom Corporation" },
    { "8F", "3Y Power Technology" },
    { "10", "Scaleo Chip" },
    { "91", "Potentia Power Systems" },
    { "92", "C-guys Incorporated" },
    { "13", "Digital Communications Technology Inc" },
    { "94", "Silicon-Based Technology" },
    { "15", "Fulcrum Microsystems" },
    { "16", "Positivo Informatica Ltd" },
    { "97", "XIOtech Corporation" },
    { "98", "PortalPlayer" },
    { "19", "Zhiying Software" },
    { "1A", "ParkerVision Inc" },
    { "9B", "Phonex Broadband" },
    { "1C", "Skyworks Solutions" },
    { "9D", "Entropic Communications" },
    { "9E", "I’M Intelligent Memory Ltd" },
    { "1F", "Zensys A/S" },
    { "20", "Legend Silicon Corp" },
    { "A1", "Sci-worx GmbH" },
    { "A2", "SMSC (Standard Microsystems)" },
    { "23", "Renesas Electronics" },
    { "A4", "Raza Microelectronics" },
    { "25", "Phyworks" },
    { "26", "MediaTek" },
    { "A7", "Non-cents Productions" },
    { "A8", "US Modular" },
    { "29", "Wintegra Ltd" },
    { "2A", "Mathstar" },
    { "AB", "StarCore" },
    { "2C", "Oplus Technologies" },
    { "AD", "Mindspeed" },
    { "AE", "Just Young Computer" },
    { "2F", "Radia Communications" },
    { "B0", "OCZ" },
    { "31", "Emuzed" },
    { "32", "LOGIC Devices" },
    { "B3", "Inphi Corporation" },
    { "34", "Quake Technologies" },
    { "B5", "Vixel" },
    { "B6", "SolusTek" },
    { "37", "Kongsberg Maritime" },
    { "38", "Faraday Technology" },
    { "B9", "Altium Ltd" },
    { "BA", "Insyte" },
    { "3B", "ARM Ltd" },
    { "BC", "DigiVision" },
    { "3D", "Vativ Technologies" },
    { "3E", "Endicott Interconnect Technologies" },
    { "BF", "Pericom" },
    { "40", "Bandspeed" },
    { "C1", "LeWiz Communications" },
    { "C2", "CPU Technology" },
    { "43", "Ramaxel Technology" },
    { "C4", "DSP Group" },
    { "45", "Axis Communications" },
    { "46", "Legacy Electronics" },
    { "C7", "Chrontel" },
    { "C8", "Powerchip Semiconductor" },
    { "49", "MobilEye Technologies" },
    { "4A", "Excel Semiconductor" },
    { "CB", "A-DATA Technology" },
    { "4C", "VirtualDigm" },
    { "CD", "G Skill Intl" },
    { "CE", "Quanta Computer" },
    { "4F", "Yield Microelectronics" },
    { "D0", "Afa Technologies" },
    { "51", "KINGBOX Technology Co Ltd" },
    { "52", "Ceva" },
    { "D3", "iStor Networks" },
    { "54", "Advance Modules" },
    { "D5", "Microsoft" },
    { "D6", "Open-Silicon" },
    { "57", "Goal Semiconductor" },
    { "58", "ARC International" },
    { "D9", "Simmtec" },
    { "DA", "Metanoia" },
    { "5B", "Key Stream" },
    { "DC", "Lowrance Electronics" },
    { "5D", "Adimos" },
    { "5E", "SiGe Semiconductor" },
    { "DF", "Fodus Communications" },
    { "E0", "Credence Systems Corp" },
    { "61", "Genesis Microchip Inc" },
    { "62", "Vihana Inc" },
    { "E3", "WIS Technologies" },
    { "64", "GateChange Technologies" },
    { "E5", "High Density Devices AS" },
    { "E6", "Synopsys" },
    { "67", "Gigaram" },
    { "68", "Enigma Semiconductor Inc" },
    { "E9", "Century Micro Inc" },
    { "EA", "Icera Semiconductor" },
    { "6B", "Mediaworks Integrated Systems" },
    { "EC", "O’Neil Product Development" },
    { "6D", "Supreme Top Technology Ltd" },
    { "6E", "MicroDisplay Corporation" },
    { "EF", "Team Group Inc" },
    { "70", "Sinett Corporation" },
    { "F1", "Toshiba Corporation" },
    { "F2", "Tensilica" },
    { "73", "SiRF Technology" },
    { "F4", "Bacoc Inc" },
    { "75", "SMaL Camera Technologies" },
    { "76", "Thomson SC" },
    { "F7", "Airgo Networks" },
    { "F8", "Wisair Ltd" },
    { "79", "SigmaTel" },
    { "7A", "Arkados" },
    { "FB", "Compete IT gmbH Co KG" },
    { "7C", "Eudar Technology Inc" },
    { "FD", "Focus Enhancements" },
    { "FE", "Xyratex" },
};

// Continuation 5
std::unordered_map<std::string, std::string> bank6 {
    { "01", "Specular Networks" },
    { "02", "Patriot Memory (PDP Systems)" },
    { "83", "U-Chip Technology Corp" },
    { "04", "Silicon Optix" },
    { "85", "Greenfield Networks" },
    { "86", "CompuRAM GmbH" },
    { "07", "Stargen Inc" },
    { "08", "NetCell Corporation" },
    { "89", "Excalibrus Technologies Ltd" },
    { "8A", "SCM Microsystems" },
    { "0B", "Xsigo Systems Inc" },
    { "8C", "CHIPS & Systems Inc" },
    { "0D", "Tier 1 Multichip Solutions" },
    { "0E", "CWRL Labs" },
    { "8F", "Teradici" },
    { "10", "Gigaram Inc" },
    { "91", "g2 Microsystems" },
    { "92", "PowerFlash Semiconductor" },
    { "13", "P.A. Semi Inc" },
    { "94", "NovaTech Solutions S.A." },
    { "15", "c2 Microsystems Inc" },
    { "16", "Level5 Networks" },
    { "97", "COS Memory AG" },
    { "98", "Innovasic Semiconductor" },
    { "19", "02IC Co Ltd" },
    { "1A", "Tabula Inc" },
    { "9B", "Crucial Technology" },
    { "1C", "Chelsio Communications" },
    { "9D", "Solarflare Communications" },
    { "9E", "Xambala Inc" },
    { "1F", "EADS Astrium" },
    { "20", "Terra Semiconductor Inc" },
    { "A1", "Imaging Works Inc" },
    { "A2", "Astute Networks Inc" },
    { "23", "Tzero" },
    { "A4", "Emulex" },
    { "25", "Power-One" },
    { "26", "Pulse~LINK Inc" },
    { "A7", "Hon Hai Precision Industry" },
    { "A8", "White Rock Networks Inc" },
    { "29", "Telegent Systems USA Inc" },
    { "2A", "Atrua Technologies Inc" },
    { "AB", "Acbel Polytech Inc" },
    { "2C", "eRide Inc" },
    { "AD", "ULi Electronics Inc" },
    { "AE", "Magnum Semiconductor Inc" },
    { "2F", "neoOne Technology Inc" },
    { "B0", "Connex Technology Inc" },
    { "31", "Stream Processors Inc" },
    { "32", "Focus Enhancements" },
    { "B3", "Telecis Wireless Inc" },
    { "34", "uNav Microelectronics" },
    { "B5", "Tarari Inc" },
    { "B6", "Ambric Inc" },
    { "37", "Newport Media Inc" },
    { "38", "VMTS" },
    { "B9", "Enuclia Semiconductor Inc" },
    { "BA", "Virtium Technology Inc" },
    { "3B", "Solid State System Co Ltd" },
    { "BC", "Kian Tech LLC" },
    { "3D", "Artimi" },
    { "3E", "Power Quotient International" },
    { "BF", "Avago Technologies" },
    { "40", "ADTechnology" },
    { "C1", "Sigma Designs" },
    { "C2", "SiCortex Inc" },
    { "43", "Ventura Technology Group" },
    { "C4", "eASIC" },
    { "45", "M.H.S. SAS" },
    { "46", "Micro Star International" },
    { "C7", "Rapport Inc" },
    { "C8", "Makway International" },
    { "49", "Broad Reach Engineering Co" },
    { "4A", "Semiconductor Mfg Intl Corp" },
    { "CB", "SiConnect" },
    { "4C", "FCI USA Inc" },
    { "CD", "Validity Sensors" },
    { "CE", "Coney Technology Co Ltd" },
    { "4F", "Spans Logic" },
    { "D0", "Neterion Inc" },
    { "51", "Qimonda" },
    { "52", "New Japan Radio Co Ltd" },
    { "D3", "Velogix" },
    { "54", "Montalvo Systems" },
    { "D5", "iVivity Inc" },
    { "D6", "Walton Chaintech" },
    { "57", "AENEON" },
    { "58", "Lorom Industrial Co Ltd" },
    { "D9", "Radiospire Networks" },
    { "DA", "Sensio Technologies Inc" },
    { "5B", "Nethra Imaging" },
    { "DC", "Hexon Technology Pte Ltd" },
    { "5D", "CompuStocx (CSX)" },
    { "5E", "Methode Electronics Inc" },
    { "DF", "Connect One Ltd" },
    { "E0", "Opulan Technologies" },
    { "61", "Septentrio NV" },
    { "62", "Goldenmars Technology Inc" },
    { "E3", "Kreton Corporation" },
    { "64", "Cochlear Ltd" },
    { "E5", "Altair Semiconductor" },
    { "E6", "NetEffect Inc" },
    { "67", "Spansion Inc" },
    { "68", "Taiwan Semiconductor Mfg" },
    { "E9", "Emphany Systems Inc" },
    { "EA", "ApaceWave Technologies" },
    { "6B", "Mobilygen Corporation" },
    { "EC", "Tego" },
    { "6D", "Cswitch Corporation" },
    { "6E", "Haier (Beijing) IC Design Co" },
    { "EF", "MetaRAM" },
    { "70", "Axel Electronics Co Ltd" },
    { "F1", "Tilera Corporation" },
    { "F2", "Aquantia" },
    { "73", "Vivace Semiconductor" },
    { "F4", "Redpine Signals" },
    { "75", "Octalica" },
    { "76", "InterDigital Communications" },
    { "F7", "Avant Technology" },
    { "F8", "Asrock Inc" },
    { "79", "Availink" },
    { "7A", "Quartics Inc" },
    { "FB", "Element CXI" },
    { "7C", "Innovaciones Microelectronicas" },
    { "FD", "VeriSilicon Microelectronics" },
    { "FE", "W5 Networks" },
};

// Continuation 6
std::unordered_map<std::string, std::string> bank7 {
    { "01", "MOVEKING" },
    { "02", "Mavrix Technology Inc" },
    { "83", "CellGuide Ltd" },
    { "04", "Faraday Technology" },
    { "85", "Diablo Technologies Inc" },
    { "86", "Jennic" },
    { "07", "Octasic" },
    { "08", "Molex Incorporated" },
    { "89", "3Leaf Networks" },
    { "8A", "Bright Micron Technology" },
    { "0B", "Netxen" },
    { "8C", "NextWave Broadband Inc" },
    { "0D", "DisplayLink" },
    { "0E", "ZMOS Technology" },
    { "8F", "Tec-Hill" },
    { "10", "Multigig Inc" },
    { "91", "Amimon" },
    { "92", "Euphonic Technologies Inc" },
    { "13", "BRN Phoenix" },
    { "94", "InSilica" },
    { "15", "Ember Corporation" },
    { "16", "Avexir Technologies Corporation" },
    { "97", "Echelon Corporation" },
    { "98", "Edgewater Computer Systems" },
    { "19", "XMOS Semiconductor Ltd" },
    { "1A", "GENUSION Inc" },
    { "9B", "Memory Corp NV" },
    { "1C", "SiliconBlue Technologies" },
    { "9D", "Rambus Inc" },
    { "9E", "Andes Technology Corporation" },
    { "1F", "Coronis Systems" },
    { "20", "Achronix Semiconductor" },
    { "A1", "Siano Mobile Silicon Ltd" },
    { "A2", "Semtech Corporation" },
    { "23", "Pixelworks Inc" },
    { "A4", "Gaisler Research AB" },
    { "25", "Teranetics" },
    { "26", "Toppan Printing Co Ltd" },
    { "A7", "Kingxcon" },
    { "A8", "Silicon Integrated Systems" },
    { "29", "I-O Data Device Inc" },
    { "2A", "NDS Americas Inc" },
    { "AB", "Solomon Systech Limited" },
    { "2C", "On Demand Microelectronics" },
    { "AD", "Amicus Wireless Inc" },
    { "AE", "SMARDTV SNC" },
    { "2F", "Comsys Communication Ltd" },
    { "B0", "Movidia Ltd" },
    { "31", "Javad GNSS Inc" },
    { "32", "Montage Technology Group" },
    { "B3", "Trident Microsystems" },
    { "34", "Super Talent" },
    { "B5", "Optichron Inc" },
    { "B6", "Future Waves UK Ltd" },
    { "37", "SiBEAM Inc" },
    { "38", "InicoreInc" },
    { "B9", "Virident Systems" },
    { "BA", "M2000 Inc" },
    { "3B", "ZeroG Wireless Inc" },
    { "BC", "Gingle Technology Co Ltd" },
    { "3D", "Space Micro Inc" },
    { "3E", "Wilocity" },
    { "BF", "Novafora Inc" },
    { "40", "iKoa Corporation" },
    { "C1", "ASint Technology" },
    { "C2", "Ramtron" },
    { "43", "Plato Networks Inc" },
    { "C4", "IPtronics AS" },
    { "45", "Infinite-Memories" },
    { "46", "Parade Technologies Inc" },
    { "C7", "Dune Networks" },
    { "C8", "GigaDevice Semiconductor" },
    { "49", "Modu Ltd" },
    { "4A", "CEITEC" },
    { "CB", "Northrop Grumman" },
    { "4C", "XRONET Corporation" },
    { "CD", "Sicon Semiconductor AB" },
    { "CE", "Atla Electronics Co Ltd" },
    { "4F", "TOPRAM Technology" },
    { "D0", "Silego Technology Inc" },
    { "51", "Kinglife" },
    { "52", "Ability Industries Ltd" },
    { "D3", "Silicon Power Computer & Communications" },
    { "54", "Augusta Technology Inc" },
    { "D5", "Nantronics Semiconductors" },
    { "D6", "Hilscher Gesellschaft" },
    { "57", "Quixant Ltd" },
    { "58", "Percello Ltd" },
    { "D9", "NextIO Inc" },
    { "DA", "Scanimetrics Inc" },
    { "5B", "FS-Semi Company Ltd" },
    { "DC", "Infinera Corporation" },
    { "5D", "SandForce Inc" },
    { "5E", "Lexar Media" },
    { "DF", "Teradyne Inc" },
    { "E0", "Memory Exchange Corp" },
    { "61", "Suzhou Smartek Electronics" },
    { "62", "Avantium Corporation" },
    { "E3", "ATP Electronics Inc" },
    { "64", "Valens Semiconductor Ltd" },
    { "E5", "Agate Logic Inc" },
    { "E6", "Netronome" },
    { "67", "Zenverge Inc" },
    { "68", "N-trig Ltd" },
    { "E9", "SanMax Technologies Inc" },
    { "EA", "Contour Semiconductor Inc" },
    { "6B", "TwinMOS" },
    { "EC", "Silicon Systems Inc" },
    { "6D", "V-Color Technology Inc" },
    { "6E", "Certicom Corporation" },
    { "EF", "JSC ICC Milandr" },
    { "70", "PhotoFast Global Inc" },
    { "F1", "InnoDisk Corporation" },
    { "F2", "Muscle Power" },
    { "73", "Energy Micro" },
    { "F4", "Innofidei" },
    { "75", "CopperGate Communications" },
    { "76", "Holtek Semiconductor Inc" },
    { "F7", "Myson Century Inc" },
    { "F8", "FIDELIX" },
    { "79", "Red Digital Cinema" },
    { "7A", "Densbits Technology" },
    { "FB", "Zempro" },
    { "7C", "MoSys" },
    { "FD", "Provigent" },
    { "FE", "Triad Semiconductor Inc" },
};

// Continuation 7
std::unordered_map<std::string, std::string> bank8 {
    { "01", "Siklu Communication Ltd" },
    { "02", "A Force Manufacturing Ltd" },
    { "83", "Strontium" },
    { "04", "ALi Corp (Abilis Systems)" },
    { "85", "Siglead Inc" },
    { "86", "Ubicom Inc" },
    { "07", "Unifosa Corporation" },
    { "08", "Stretch Inc" },
    { "89", "Lantiq Deutschland GmbH" },
    { "8A", "Visipro." },
    { "0B", "EKMemory" },
    { "8C", "Microelectronics Institute ZTE" },
    { "0D", "u-blox AG" },
    { "0E", "Carry Technology Co Ltd" },
    { "8F", "Nokia" },
    { "10", "King Tiger Technology" },
    { "91", "Sierra Wireless" },
    { "92", "HT Micron" },
    { "13", "Albatron Technology Co Ltd" },
    { "94", "Leica Geosystems AG" },
    { "15", "BroadLight" },
    { "16", "AEXEA" },
    { "97", "ClariPhy Communications Inc" },
    { "98", "Green Plug" },
    { "19", "Design Art Networks" },
    { "1A", "Mach Xtreme Technology Ltd" },
    { "9B", "ATO Solutions Co Ltd" },
    { "1C", "Ramsta" },
    { "9D", "Greenliant Systems Ltd" },
    { "9E", "Teikon" },
    { "1F", "Antec Hadron" },
    { "20", "NavCom Technology Inc" },
    { "A1", "Shanghai Fudan Microelectronics" },
    { "A2", "Calxeda Inc" },
    { "23", "JSC EDC Electronics" },
    { "A4", "Kandit Technology Co Ltd" },
    { "25", "Ramos Technology" },
    { "26", "Goldenmars Technology" },
    { "A7", "XeL Technology Inc" },
    { "A8", "Newzone Corporation" },
    { "29", "ShenZhen MercyPower Tech" },
    { "2A", "Nanjing Yihuo Technology" },
    { "AB", "Nethra Imaging Inc" },
    { "2C", "SiTel Semiconductor BV" },
    { "AD", "SolidGear Corporation" },
    { "AE", "Topower Computer Ind Co Ltd" },
    { "2F", "Wilocity" },
    { "B0", "Profichip GmbH" },
    { "31", "Gerad Technologies" },
    { "32", "Ritek Corporation" },
    { "B3", "Gomos Technology Limited" },
    { "34", "Memoright Corporation" },
    { "B5", "D-Broad Inc" },
    { "B6", "HiSilicon Technologies" },
    { "37", "Syndiant Inc." },
    { "38", "Enverv Inc" },
    { "B9", "Cognex" },
    { "BA", "Xinnova Technology Inc" },
    { "3B", "Ultron AG" },
    { "BC", "Concord Idea Corporation" },
    { "3D", "AIM Corporation" },
    { "3E", "Lifetime Memory Products" },
    { "BF", "Ramsway" },
    { "40", "Recore Systems B.V." },
    { "C1", "Haotian Jinshibo Science Tech" },
    { "C2", "Being Advanced Memory" },
    { "43", "Adesto Technologies" },
    { "C4", "Giantec Semiconductor Inc" },
    { "45", "HMD Electronics AG" },
    { "46", "Gloway International (HK)" },
    { "C7", "Kingcore" },
    { "C8", "Anucell Technology Holding" },
    { "49", "Accord Software & Systems Pvt. Ltd" },
    { "4A", "Active-Semi Inc" },
    { "CB", "Denso Corporation" },
    { "4C", "TLSI Inc" },
    { "CD", "Qidan" },
    { "CE", "Mustang" },
    { "4F", "Orca Systems" },
    { "D0", "Passif Semiconductor" },
    { "51", "GigaDevice Semiconductor (Beijing)" },
    { "52", "Memphis Electronic" },
    { "D3", "Beckhoff Automation GmbH" },
    { "54", "Harmony Semiconductor Corp" },
    { "D5", "Air Computers SRL" },
    { "D6", "TMT Memory" },
    { "57", "Eorex Corporation" },
    { "58", "Xingtera" },
    { "D9", "Netsol" },
    { "DA", "Bestdon Technology Co Ltd" },
    { "5B", "Baysand Inc" },
    { "DC", "Uroad Technology Co Ltd" },
    { "5D", "Wilk Elektronik S.A." },
    { "5E", "AAI" },
    { "DF", "Harman" },
    { "E0", "Berg Microelectronics Inc" },
    { "61", "ASSIA Inc" },
    { "62", "Visiontek Products LLC" },
    { "E3", "OCMEMORY" },
    { "64", "Welink Solution Inc" },
    { "E5", "Shark Gaming" },
    { "E6", "Avalanche Technology" },
    { "67", "R&D Center ELVEES OJSC" },
    { "68", "KingboMars Technology Co Ltd" },
    { "E9", "High Bridge Solutions Industria Eletronica" },
    { "EA", "Transcend Technology Co Ltd" },
    { "6B", "Everspin Technologies" },
    { "EC", "Hon-Hai Precision" },
    { "6D", "Smart Storage Systems" },
    { "6E", "Toumaz Group" },
    { "EF", "Zentel Electronics Corporation" },
    { "70", "Panram International Corporation" },
    { "F1", "Silicon Space Technology" },
    { "F2", "LITE-ON IT Corporation" },
    { "73", "Inuitive" },
    { "F4", "HMicro" },
    { "75", "BittWare Inc" },
    { "76", "GLOBALFOUNDRIES" },
    { "F7", "ACPI Digital Co Ltd" },
    { "F8", "Annapurna Labs" },
    { "79", "AcSiP Technology Corporation" },
    { "7A", "Idea! Electronic Systems" },
    { "FB", "Gowe Technology Co Ltd" },
    { "7C", "Hermes Testing Solutions Inc" },
    { "FD", "Positivo BGH" },
    { "FE", "Intelligence Silicon Technology" },
};

// Continuation 8
std::unordered_map<std::string, std::string> bank9 {
    { "01", "3D PLUS" },
    { "02", "Diehl Aerospace" },
    { "83", "Fairchild" },
    { "04", "Mercury Systems" },
    { "85", "Sonics Inc" },
    { "86", "Emerson Automation Solutions" },
    { "07", "Shenzhen Jinge Information Co Ltd" },
    { "08", "SCWW" },
    { "89", "Silicon Motion Inc" },
    { "8A", "Anurag" },
    { "0B", "King Kong" },
    { "8C", "FROM30 Co Ltd" },
    { "0D", "Gowin Semiconductor Corp" },
    { "0E", "Fremont Micro Devices Ltd" },
    { "8F", "Ericsson Modems" },
    { "10", "Exelis" },
    { "91", "Satixfy Ltd" },
    { "92", "Galaxy Microsystems Ltd" },
    { "13", "Gloway International Co Ltd" },
    { "94", "Lab" },
    { "15", "Smart Energy Instruments" },
    { "16", "Approved Memory Corporation" },
    { "97", "Axell Corporation" },
    { "98", "Essencore Limited" },
    { "19", "Phytium" },
    { "1A", "Xi’an UniIC Semiconductors Co Ltd" },
    { "9B", "Ambiq Micro" },
    { "1C", "eveRAM Technology Inc" },
    { "9D", "Infomax" },
    { "9E", "Butterfly Network Inc" },
    { "1F", "Shenzhen City Gcai Electronics" },
    { "20", "Stack Devices Corporation" },
    { "A1", "ADK Media Group" },
    { "A2", "TSP Global Co Ltd" },
    { "23", "HighX" },
    { "A4", "Shenzhen Elicks Technology" },
    { "25", "XinKai/Silicon Kaiser" },
    { "26", "Google Inc" },
    { "A7", "Dasima International Development" },
    { "A8", "Leahkinn Technology Limited" },
    { "29", "HIMA Paul Hildebrandt GmbH Co KG" },
    { "2A", "Keysight Technologies" },
    { "AB", "Techcomp International (Fastable)" },
    { "2C", "Ancore Technology Corporation" },
    { "AD", "Nuvoton" },
    { "AE", "Korea Uhbele International Group Ltd" },
    { "2F", "Ikegami Tsushinki Co Ltd" },
    { "B0", "RelChip Inc" },
    { "31", "Baikal Electronics" },
    { "32", "Nemostech Inc" },
    { "B3", "Memorysolution GmbH" },
    { "34", "Silicon Integrated Systems Corporation" },
    { "B5", "Xiede" },
    { "B6", "BRC" },
    { "37", "Flash Chi" },
    { "38", "Jone" },
    { "B9", "GCT Semiconductor Inc" },
    { "BA", "Hong Kong Zetta Device Technology" },
    { "3B", "Unimemory Technology(s) Pte Ltd" },
    { "BC", "Cuso" },
    { "3D", "Kuso" },
    { "3E", "Uniquify Inc" },
    { "BF", "Skymedi Corporation" },
    { "40", "Core Chance Co Ltd" },
    { "C1", "Tekism Co Ltd" },
    { "C2", "Seagate Technology PLC" },
    { "43", "Hong Kong Gaia Group Co Limited" },
    { "C4", "Gigacom Semiconductor LLC" },
    { "45", "V2 Technologies" },
    { "46", "TLi" },
    { "C7", "Neotion" },
    { "C8", "Lenovo" },
    { "49", "Shenzhen Zhongteng Electronic Corp Ltd" },
    { "4A", "Compound Photonics" },
    { "CB", "in2H2 inc" },
    { "4C", "Shenzhen Pango Microsystems Co Ltd" },
    { "CD", "Vasekey" },
    { "CE", "Cal-Comp Industria de Semicondutores" },
    { "4F", "Eyenix Co Ltd" },
    { "D0", "Heoriady" },
    { "51", "Accelerated Memory Production Inc" },
    { "52", "INVECAS Inc" },
    { "D3", "AP Memory" },
    { "54", "Douqi Technology" },
    { "D5", "Etron Technology Inc" },
    { "D6", "Indie Semiconductor" },
    { "57", "Socionext Inc" },
    { "58", "HGST" },
    { "D9", "EVGA" },
    { "DA", "Audience Inc" },
    { "5B", "EpicGear" },
    { "DC", "Vitesse Enterprise Co" },
    { "5D", "Foxtronn International Corporation" },
    { "5E", "Bretelon Inc" },
    { "DF", "Graphcore" },
    { "E0", "Eoplex Inc" },
    { "61", "MaxLinear Inc" },
    { "62", "ETA Devices" },
    { "E3", "LOKI" },
    { "64", "IMS Electronics Co Ltd" },
    { "E5", "Dosilicon Co Ltd" },
    { "E6", "Dolphin Integration" },
    { "67", "Shenzhen Mic Electronics Technolog" },
    { "68", "Boya Microelectronics Inc" },
    { "E9", "Geniachip (Roche)" },
    { "EA", "Axign" },
    { "6B", "Kingred Electronic Technology Ltd" },
    { "EC", "Chao Yue Zhuo Computer Business Dept." },
    { "6D", "Guangzhou Si Nuo Electronic Technology." },
    { "6E", "Crocus Technology Inc" },
    { "EF", "Creative Chips GmbH" },
    { "70", "GE Aviation Systems LLC." },
    { "F1", "Asgard" },
    { "F2", "Good Wealth Technology Ltd" },
    { "73", "TriCor Technologies" },
    { "F4", "Nova-Systems GmbH" },
    { "75", "JUHOR" },
    { "76", "Zhuhai Douke Commerce Co Ltd" },
    { "F7", "DSL Memory" },
    { "F8", "Anvo-Systems Dresden GmbH" },
    { "79", "Realtek" },
    { "7A", "AltoBeam" },
    { "FB", "Wave Computing" },
    { "7C", "Beijing TrustNet Technology Co Ltd" },
    { "FD", "Innovium Inc" },
    { "FE", "Starsway Technology Limited" },
};

// Continuation 9
std::unordered_map<std::string, std::string> bank10 {
    { "01", "Weltronics Co LTD" },
    { "02", "VMware Inc" },
    { "83", "Hewlett Packard Enterprise" },
    { "04", "INTENSO" },
    { "85", "Puya Semiconductor" },
    { "86", "MEMORFI" },
    { "07", "MSC Technologies GmbH" },
    { "08", "Txrui" },
    { "89", "SiFive Inc" },
    { "8A", "Spreadtrum Communications" },
    { "0B", "XTX Technology Limited" },
    { "8C", "UMAX Technology" },
    { "0D", "Shenzhen Yong Sheng Technology" },
    { "0E", "SNOAMOO (Shenzhen Kai Zhuo Yue)" },
    { "8F", "Daten Tecnologia LTDA" },
    { "10", "Shenzhen XinRuiYan Electronics" },
    { "91", "Eta Compute" },
    { "92", "Energous" },
    { "13", "Raspberry Pi Trading Ltd" },
    { "94", "Shenzhen Chixingzhe Tech Co Ltd" },
    { "15", "Silicon Mobility" },
    { "16", "IQ-Analog Corporation" },
    { "97", "Uhnder Inc" },
    { "98", "Impinj" },
    { "19", "DEPO Computers" },
    { "1A", "Nespeed Sysems" },
    { "9B", "Yangtze Memory Technologies Co Ltd" },
    { "1C", "MemxPro Inc" },
    { "9D", "Tammuz Co Ltd" },
    { "9E", "Allwinner Technology" },
    { "1F", "Shenzhen City Futian District Qing Xuan Tong Computer Trading Firm" },
    { "20", "XMC" },
    { "A1", "Teclast" },
    { "A2", "Maxsun" },
    { "23", "Haiguang Integrated Circuit Design" },
    { "A4", "RamCENTER Technology" },
    { "25", "Phison Electronics Corporation" },
    { "26", "Guizhou Huaxintong Semi-Conductor" },
    { "A7", "Network Intelligence" },
    { "A8", "Continental Technology (Holdings)" },
    { "29", "Guangzhou Huayan Suning Electronic" },
    { "2A", "Guangzhou Zhouji Electronic Co Ltd" },
    { "AB", "Shenzhen Giant Hui Kang Tech Co Ltd" },
    { "2C", "Shenzhen Yilong Innovative Co Ltd" },
    { "AD", "Neo Forza" },
    { "AE", "Lyontek Inc" },
    { "2F", "Shanghai Kuxin Microelectronics Ltd" },
    { "B0", "Shenzhen Larix Technology Co Ltd" },
    { "31", "Qbit Semiconductor Ltd" },
    { "32", "Insignis Technology Corporation" },
    { "B3", "Lanson Memory Co Ltd" },
    { "34", "Shenzhen Superway Electronics Co Ltd" },
    { "B5", "Canaan-Creative Co Ltd" },
    { "B6", "Black Diamond Memory" },
    { "37", "Shenzhen City Parker Baking Electronics" },
    { "38", "Shenzhen Baihong Technology Co Ltd" },
    { "B9", "GEO Semiconductors" },
    { "BA", "OCPC" },
    { "3B", "Artery Technology Co Ltd" },
    { "BC", "Jinyu" },
    { "3D", "ShenzhenYing Chi Technology Development" },
    { "3E", "Shenzhen Pengcheng Xin Technology" },
    { "BF", "Pegasus Semiconductor (Shanghai) Co" },
    { "40", "Mythic Inc" },
    { "C1", "Elmos Semiconductor AG" },
    { "C2", "Kllisre" },
    { "43", "Shenzhen Winconway Technology" },
    { "C4", "Shenzhen Xingmem Technology Corp" },
    { "45", "Gold Key Technology Co Ltd" },
    { "46", "Habana Labs Ltd" },
    { "C7", "Hoodisk Electronics Co Ltd" },
    { "C8", "SemsoTai (SZ) Technology Co Ltd" },
    { "49", "OM Nanotech Pvt. Ltd" },
    { "4A", "Shenzhen Zhifeng Weiye Technology" },
    { "CB", "Xinshirui (Shenzhen) Electronics Co" },
    { "4C", "Guangzhou Zhong Hao Tian Electronic" },
    { "CD", "Shenzhen Longsys Electronics Co Ltd" },
    { "CE", "Deciso B.V." },
    { "4F", "Puya Semiconductor (Shenzhen)" },
    { "D0", "Shenzhen Veineda Technology Co Ltd" },
    { "51", "Antec Memory" },
    { "52", "Cortus SAS" },
    { "D3", "Dust Leopard" },
    { "54", "MyWo AS" },
    { "D5", "J&A Information Inc" },
    { "D6", "Shenzhen JIEPEI Technology Co Ltd" },
    { "57", "Heidelberg University" },
    { "58", "Flexxon PTE Ltd" },
    { "D9", "Wiliot" },
    { "DA", "Raysun Electronics International Ltd" },
    { "5B", "Aquarius Production Company LLC" },
    { "DC", "MACNICA DHW LTDA" },
    { "5D", "Intelimem" },
    { "5E", "Zbit Semiconductor Inc" },
    { "DF", "Shenzhen Technology Co Ltd" },
    { "E0", "Signalchip" },
    { "61", "Shenzen Recadata Storage Technology" },
    { "62", "Hyundai Technology" },
    { "E3", "Shanghai Fudi Investment Development" },
    { "64", "Aixi Technology" },
    { "E5", "Tecon MT" },
    { "E6", "Onda Electric Co Ltd" },
    { "67", "Jinshen" },
    { "68", "Kimtigo Semiconductor (HK) Limited" },
    { "E9", "IIT Madras" },
    { "EA", "Shenshan (Shenzhen) Electronic" },
    { "6B", "Hefei Core Storage Electronic Limited" },
    { "EC", "Colorful Technology Ltd" },
    { "6D", "Visenta (Xiamen) Technology Co Ltd" },
    { "6E", "Roa Logic BV" },
    { "EF", "NSITEXE Inc" },
    { "70", "Hong Kong Hyunion Electronics" },
    { "F1", "ASK Technology Group Limited" },
    { "F2", "GIGA-BYTE Technology Co Ltd" },
    { "73", "Terabyte Co Ltd" },
    { "F4", "Hyundai Inc" },
    { "75", "EXCELERAM" },
    { "76", "PsiKick" },
    { "F7", "Netac Technology Co Ltd" },
    { "F8", "PCCOOLER" },
    { "79", "Jiangsu Huacun Electronic Technology" },
    { "7A", "Shenzhen Micro Innovation Industry" },
    { "FB", "Beijing Tongfang Microelectronics Co" },
    { "7C", "XZN Storage Technology" },
    { "FD", "ChipCraft Sp. z.o.o." },
    { "FE", "ALLFLASH Technology Limited" },
};

// Continuation 10
std::unordered_map<std::string, std::string> bank11 {
    { "01", "Foerd Technology Co Ltd" },
    { "02", "KingSpec" },
    { "83", "Codasip GmbH" },
    { "04", "SL Link Co Ltd" },
    { "85", "Shenzhen Kefu Technology Co Limited" },
    { "86", "Shenzhen ZST Electronics Technology" },
    { "07", "Kyokuto Electronic Inc" },
    { "08", "Warrior Technology" },
    { "89", "TRINAMIC Motion Control GmbH & Co" },
    { "8A", "PixelDisplay Inc" },
    { "0B", "Shenzhen Futian District Bo Yueda Elec" },
    { "8C", "Richtek Power" },
    { "0D", "Shenzhen LianTeng Electronics Co Ltd" },
    { "0E", "AITC Memory" },
    { "8F", "UNIC Memory Technology Co Ltd" },
    { "10", "Shenzhen Huafeng Science Technology" },
    { "91", "CXMT" },
    { "92", "Guangzhou Xinyi Heng Computer Trading Firm" },
    { "13", "SambaNova Systems" },
    { "94", "V-GEN" },
    { "15", "Jump Trading" },
    { "16", "Ampere Computing" },
    { "97", "Shenzhen Zhongshi Technology Co Ltd" },
    { "98", "Shenzhen Zhongtian Bozhong Technology" },
    { "19", "Tri-Tech International" },
    { "1A", "Silicon Intergrated Systems Corporation" },
    { "9B", "Shenzhen HongDingChen Information" },
    { "1C", "Plexton Holdings Limited" },
    { "9D", "AMS (Jiangsu Advanced Memory Semi)" },
    { "9E", "Wuhan Jing Tian Interconnected Tech Co" },
    { "1F", "Axia Memory Technology" },
    { "20", "Chipset Technology Holding Limited" },
    { "A1", "Shenzhen Xinshida Technology Co Ltd" },
    { "A2", "Shenzhen Chuangshifeida Technology" },
    { "23", "Guangzhou MiaoYuanJi Technology" },
    { "A4", "ADVAN Inc" },
    { "25", "Shenzhen Qianhai Weishengda Electronic Commerce Company Ltd" },
    { "26", "Guangzhou Guang Xie Cheng Trading" },
    { "A7", "StarRam International Co Ltd" },
    { "A8", "Shen Zhen XinShenHua Tech Co Ltd" },
    { "29", "UltraMemory Inc" },
    { "2A", "New Coastline Global Tech Industry Co" },
    { "AB", "Sinker" },
    { "2C", "Diamond" },
    { "AD", "PUSKILL" },
    { "AE", "Guangzhou Hao Jia Ye Technology Co" },
    { "2F", "Ming Xin Limited" },
    { "B0", "Barefoot Networks" },
    { "31", "Biwin Semiconductor (HK) Co Ltd" },
    { "32", "UD INFO Corporation" },
    { "B3", "Trek Technology (S) PTE Ltd" },
    { "34", "Xiamen Kingblaze Technology Co Ltd" },
    { "B5", "Shenzhen Lomica Technology Co Ltd" },
    { "B6", "Nuclei System Technology Co Ltd" },
    { "37", "Wuhan Xun Zhan Electronic Technology" },
    { "38", "Shenzhen Ingacom Semiconductor Ltd" },
    { "B9", "Zotac Technology Ltd" },
    { "BA", "Foxline" },
    { "3B", "Shenzhen Farasia Science Technology" },
    { "BC", "Efinix Inc" },
    { "3D", "Hua Nan San Xian Technology Co Ltd" },
    { "3E", "Goldtech Electronics Co Ltd" },
    { "BF", "Shanghai Han Rong Microelectronics Co" },
    { "40", "Shenzhen Zhongguang Yunhe Trading" },
    { "C1", "Smart Shine(QingDao) Microelectronics" },
    { "C2", "Thermaltake Technology Co Ltd" },
    { "43", "Shenzhen O’Yang Maile Technology Ltd" },
    { "C4", "UPMEM" },
    { "45", "Chun Well Technology Holding Limited" },
    { "46", "Astera Labs Inc" },
    { "C7", "Winconway" },
    { "C8", "Advantech Co Ltd" },
    { "49", "Chengdu Fengcai Electronic Technology" },
    { "4A", "The Boeing Company" },
    { "CB", "Blaize Inc" },
    { "4C", "Ramonster Technology Co Ltd" },
    { "CD", "Wuhan Naonongmai Technology Co Ltd" },
    { "CE", "Shenzhen Hui ShingTong Technology" },
    { "4F", "Yourlyon" },
    { "D0", "Fabu Technology" },
    { "51", "Shenzhen Yikesheng Technology Co Ltd" },
    { "52", "NOR-MEM" },
    { "D3", "Cervoz Co Ltd" },
    { "54", "Bitmain Technologies Inc." },
    { "D5", "Facebook Inc" },
    { "D6", "Shenzhen Longsys Electronics Co Ltd" },
    { "57", "Guangzhou Siye Electronic Technology" },
    { "58", "Silergy" },
    { "D9", "Adamway" },
    { "DA", "PZG" },
    { "5B", "Shenzhen King Power Electronics" },
    { "DC", "Guangzhou ZiaoFu Tranding Co Ltd" },
    { "5D", "Shenzhen SKIHOTAR Semiconductor" },
    { "5E", "PulseRain Technology" },
    { "DF", "Seeker Technology Limited" },
    { "E0", "Shenzhen OSCOO Tech Co Ltd" },
    { "61", "Shenzhen Yze Technology Co Ltd" },
    { "62", "Shenzhen Jieshuo Electronic Commerce" },
    { "E3", "Gazda" },
    { "64", "Hua Wei Technology Co Ltd" },
    { "E5", "Esperanto Technologies" },
    { "E6", "JinSheng Electronic (Shenzhen) Co Ltd" },
    { "67", "Shenzhen Shi Bolunshuai Technology" },
    { "68", "Shanghai Rei Zuan Information Tech" },
    { "E9", "Fraunhofer IIS" },
    { "EA", "Kandou Bus SA" },
    { "6B", "Acer" },
    { "EC", "Artmem Technology Co Ltd" },
    { "6D", "Gstar Semiconductor Co Ltd" },
    { "6E", "ShineDisk" },
    { "EF", "Shenzhen CHN Technology Co Ltd" },
    { "70", "UnionChip Semiconductor Co Ltd" },
    { "F1", "Tanbassh" },
    { "F2", "Shenzhen Tianyu Jieyun Intl Logistics" },
    { "73", "MCLogic Inc" },
    { "F4", "Eorex Corporation" },
    { "75", "Arm Technology (China) Co Ltd" },
    { "76", "Lexar Co Limited" },
    { "F7", "QinetiQ Group plc" },
    { "F8", "Exascend" },
    { "79", "Hong Kong Hyunion Electronics Co Ltd" },
    { "7A", "Shenzhen Banghong Electronics Co Ltd" },
    { "FB", "MBit Wireless Inc" },
    { "7C", "Hex Five Security Inc" },
    { "FD", "ShenZhen Juhor Precision Tech Co Ltd" },
    { "FE", "Shenzhen Reeinno Technology Co Ltd" },
};

// Continuation 11
std::unordered_map<std::string, std::string> bank12 {
    { "01", "ABIT Electronics (Shenzhen) Co Ltd" },
    { "02", "Semidrive" },
    { "83", "MyTek Electronics Corp" },
    { "04", "Wxilicon Technology Co Ltd" },
    { "85", "Shenzhen Meixin Electronics Ltd" },
    { "86", "Ghost Wolf" },
    { "07", "LiSion Technologies Inc" },
    { "08", "Power Active Co Ltd" },
    { "89", "Pioneer High Fidelity Taiwan Co. Ltd" },
    { "8A", "LuoSilk" },
    { "0B", "Shenzhen Chuangshifeida Technology" },
    { "8C", "Black Sesame Technologies Inc" },
    { "0D", "Jiangsu Xinsheng Intelligent Technology" },
    { "0E", "MLOONG" },
    { "8F", "Quadratica LLC" },
    { "10", "Anpec Electronics" },
    { "91", "Xi’an Morebeck Semiconductor Tech Co" },
    { "92", "Kingbank Technology Co Ltd" },
    { "13", "ITRenew Inc" },
    { "94", "Shenzhen Eaget Innovation Tech Ltd" },
    { "15", "Jazer" },
    { "16", "Xiamen Semiconductor Investment Group" },
    { "97", "Guangzhou Longdao Network Tech Co" },
    { "98", "Shenzhen Futian SEC Electronic Market" },
    { "19", "Allegro Microsystems LLC" },
    { "1A", "Hunan RunCore Innovation Technology" },
    { "9B", "C-Corsa Technology" },
    { "1C", "Zhuhai Chuangfeixin Technology Co Ltd" },
    { "9D", "Beijing InnoMem Technologies Co Ltd" },
    { "9E", "YooTin" },
    { "1F", "Shenzhen Pengxiong Technology Co Ltd" },
    { "20", "Dongguan Yingbang Commercial Trading Co" },
    { "A1", "Shenzhen Ronisys Electronics Co Ltd" },
    { "A2", "Hongkong Xinlan Guangke Co Ltd" },
    { "23", "Apex Microelectronics Co Ltd" },
    { "A4", "Beijing Hongda Jinming Technology Co Ltd" },
    { "25", "Ling Rui Technology (Shenzhen) Co Ltd" },
    { "26", "Hongkong Hyunion Electronics Co Ltd" },
    { "A7", "Starsystems Inc" },
    { "A8", "Shenzhen Yingjiaxun Industrial Co Ltd" },
    { "29", "Dongguan Crown Code Electronic Commerce" },
    { "2A", "Monolithic Power Systems Inc" },
    { "AB", "WuHan SenNaiBo E-Commerce Co Ltd" },
    { "2C", "Hangzhou Hikstorage Technology Co" },
    { "AD", "Shenzhen Goodix Technology Co Ltd" },
    { "AE", "Aigo Electronic Technology Co Ltd" },
    { "2F", "Hefei Konsemi Storage Technology Co Ltd" },
    { "B0", "Cactus Technologies Limited" },
    { "31", "DSIN" },
    { "32", "Blu Wireless Technology" },
    { "B3", "Nanjing UCUN Technology Inc" },
    { "34", "Acacia Communications" },
    { "B5", "Beijinjinshengyihe Technology Co Ltd" },
    { "B6", "Zyzyx" },
    { "37", "T-HEAD Semiconductor Co Ltd" },
    { "38", "Shenzhen Hystou Technology Co Ltd" },
    { "B9", "Syzexion" },
    { "BA", "Kembona" },
    { "3B", "Qingdao Thunderobot Technology Co Ltd" },
    { "BC", "Morse Micro" },
    { "3D", "Shenzhen Envida Technology Co Ltd" },
    { "3E", "UDStore Solution Limited" },
    { "BF", "Shunlie" },
    { "40", "Shenzhen Xin Hong Rui Tech Ltd" },
    { "C1", "Shenzhen Yze Technology Co Ltd" },
    { "C2", "Shenzhen Huang Pu He Xin Technology" },
    { "43", "Xiamen Pengpai Microelectronics Co Ltd" },
    { "C4", "JISHUN" },
    { "45", "Shenzhen WODPOSIT Technology Co" },
    { "46", "Unistar" },
    { "C7", "UNICORE Electronic (Suzhou) Co Ltd" },
    { "C8", "Axonne Inc" },
    { "49", "Shenzhen SOVERECA Technology Co" },
    { "4A", "Dire Wolf" },
    { "CB", "Whampoa Core Technology Co Ltd" },
    { "4C", "CSI Halbleiter GmbH" },
    { "CD", "ONE Semiconductor" },
    { "CE", "SimpleMachines Inc" },
    { "4F", "Shenzhen Chengyi Qingdian Electronic" },
    { "D0", "Shenzhen Xinlianxin Network Technology" },
    { "51", "Vayyar Imaging Ltd" },
    { "52", "Paisen Network Technology Co Ltd" },
    { "D3", "Shenzhen Fengwensi Technology Co Ltd" },
    { "54", "Caplink Technology Limited" },
    { "D5", "JJT Solution Co Ltd" },
    { "D6", "HOSIN Global Electronics Co Ltd" },
    { "57", "Shenzhen KingDisk Century Technology" },
    { "58", "SOYO" },
    { "D9", "DIT Technology Co Ltd" },
    { "DA", "iFound" },
    { "5B", "Aril Computer Company" },
    { "DC", "ASUS" },
    { "5D", "Shenzhen Ruiyingtong Technology Co" },
    { "5E", "HANA Micron" },
    { "DF", "RANSOR" },
    { "E0", "Axiado Corporation" },
    { "61", "Tesla Corporation" },
    { "62", "Pingtouge (Shanghai) Semiconductor Co" },
    { "E3", "S3Plus Technologies SA" },
    { "64", "Integrated Silicon Solution Israel Ltd" },
    { "E5", "GreenWaves Technologies" },
    { "E6", "NUVIA Inc" },
    { "67", "Guangzhou Shuvrwine Technology Co" },
    { "68", "Shenzhen Hangshun Chip Technology" },
    { "E9", "Chengboliwei Electronic Business" },
    { "EA", "Kowin Technology HK Limited" },
    { "6B", "Euronet Technology Inc" },
    { "EC", "SCY" },
    { "6D", "Shenzhen Xinhongyusheng Electrical" },
    { "6E", "PICOCOM" },
    { "EF", "Shenzhen Toooogo Memory Technology" },
    { "70", "VLSI Solution" },
    { "F1", "Costar Electronics Inc" },
    { "F2", "Shenzhen Huatop Technology Co Ltd" },
    { "73", "Inspur Electronic Information Industry" },
    { "F4", "Shenzhen Boyuan Computer Technology" },
    { "75", "Beijing Welldisk Electronics Co Ltd" },
    { "76", "Suzhou EP Semicon Co Ltd" },
    { "F7", "Zhejiang Dahua Memory Technology" },
    { "F8", "Virtu Financial" },
    { "79", "Datotek International Co Ltd" },
    { "7A", "Telecom and Microelectronics Industries" },
    { "FB", "Echow Technology Ltd" },
    { "7C", "APEX-INFO" },
    { "FD", "Yingpark" },
    { "FE", "Shenzhen Bigway Tech Co Ltd" },
};

// Continuation 12
std::unordered_map<std::string, std::string> bank13 {
    { "01", "Beijing Haawking Technology Co Ltd" },
    { "02", "Open HW Group" },
    { "83", "JHICC" },
    { "04", "ncoder AG" },
    { "85", "ThinkTech Information Technology Co" },
    { "86", "Shenzhen Chixingzhe Technology Co Ltd" },
    { "07", "Biao Ram Technology Co Ltd" },
    { "08", "Shenzhen Kaizhuoyue Electronics Co Ltd" },
    { "89", "Shenzhen YC Storage Technology Co Ltd" },
    { "8A", "Shenzhen Chixingzhe Technology Co" },
    { "0B", "Wink Semiconductor (Shenzhen) Co Ltd" },
    { "8C", "AISTOR" },
    { "0D", "Palma Ceia SemiDesign" },
    { "0E", "EM Microelectronic-Marin SA" },
    { "8F", "Shenzhen Monarch Memory Technology" },
    { "10", "Reliance Memory Inc" },
    { "91", "Jesis" },
    { "92", "Espressif Systems (Shanghai) Co Ltd" },
    { "13", "Shenzhen Sati Smart Technology Co Ltd" },
    { "94", "NeuMem Co Ltd" },
    { "15", "Lifelong" },
    { "16", "Beijing Oitech Technology Co Ltd" },
    { "97", "Groupe LDLC" },
    { "98", "Semidynamics Technology Services SLU" },
    { "19", "swordbill" },
    { "1A", "YIREN" },
    { "9B", "Shenzhen Yinxiang Technology Co Ltd" },
    { "1C", "PoweV Electronic Technology Co Ltd" },
    { "9D", "LEORICE" },
    { "9E", "Waymo LLC" },
    { "1F", "Ventana Micro Systems" },
    { "20", "Hefei Guangxin Microelectronics Co Ltd" },
    { "A1", "Shenzhen Sooner Industrial Co Ltd" },
    { "A2", "Horizon Robotics" },
    { "23", "Tangem AG" },
    { "A4", "FuturePath Technology (Shenzhen) Co" },
    { "25", "RC Module" },
    { "26", "Timetec International Inc" },
    { "A7", "ICMAX Technologies Co Limited" },
    { "A8", "Lynxi Technologies Ltd Co" },
    { "29", "Guangzhou Taisupanke Computer Equipment" },
    { "2A", "Ceremorphic Inc" },
    { "AB", "Biwin Storage Technology Co Ltd" },
    { "2C", "Beijing ESWIN Computing Technology" },
    { "AD", "WeForce Co Ltd" },
    { "AE", "Shenzhen Fanxiang Information Technology" },
    { "2F", "Unisoc" },
    { "B0", "YingChu" },
    { "31", "GUANCUN" },
    { "32", "IPASON" },
    { "B3", "Ayar Labs" },
    { "34", "Amazon" },
    { "B5", "Shenzhen Xinxinshun Technology Co" },
    { "B6", "Galois Inc" },
    { "37", "Ubilite Inc" },
    { "38", "Shenzhen Quanxing Technology Co Ltd" },
    { "B9", "Group RZX Technology LTDA" },
    { "BA", "Yottac Technology (XI’AN) Cooperation" },
    { "3B", "Shenzhen RuiRen Technology Co Ltd" },
    { "BC", "Group Star Technology Co Ltd" },
    { "3D", "RWA (Hong Kong) Ltd" },
    { "3E", "Genesys Logic Inc" },
    { "BF", "T3 Robotics Inc." },
    { "40", "Biostar Microtech International Corp" },
    { "C1", "Shenzhen SXmicro Technology Co Ltd" },
    { "C2", "Shanghai Yili Computer Technology Co" },
    { "43", "Zhixin Semicoducotor Co Ltd" },
    { "C4", "uFound" },
    { "45", "Aigo Data Security Technology Co. Ltd" },
    { "46", ".GXore Technologies" },
    { "C7", "Shenzhen Pradeon Intelligent Technology" },
    { "C8", "Power LSI" },
    { "49", "PRIME" },
    { "4A", "Shenzhen Juyang Innovative Technology" },
    { "CB", "CERVO" },
    { "4C", "SiEngine Technology Co., Ltd." },
    { "CD", "Beijing Unigroup Tsingteng MicroSystem" },
    { "CE", "Brainsao GmbH" },
    { "4F", "Credo Technology Group Ltd" },
    { "D0", "Shanghai Biren Technology Co Ltd" },
    { "51", "Nucleu Semiconductor" },
    { "52", "Shenzhen Guangshuo Electronics Co Ltd" },
    { "D3", "ZhongsihangTechnology Co Ltd" },
    { "54", "Suzhou Mainshine Electronic Co Ltd." },
    { "D5", "Guangzhou Riss Electronic Technology" },
    { "D6", "Shenzhen Cloud Security Storage Co" },
    { "57", "ROG" },
    { "58", "Perceive" },
    { "D9", "e-peas" },
    { "DA", "Fraunhofer IPMS" },
    { "5B", "Shenzhen Daxinlang Electronic Tech Co" },
    { "DC", "Abacus Peripherals Private Limited" },
    { "5D", "OLOy Technology" },
    { "5E", "Wuhan P&S Semiconductor Co Ltd" },
    { "DF", "Sitrus Technology" },
    { "E0", "AnHui Conner Storage Co Ltd" },
    { "61", "Rochester Electronics" },
    { "62", "Wuxi Petabyte Technologies Co Ltd" },
    { "E3", "Star Memory" },
    { "64", "Agile Memory Technology Co Ltd" },
    { "E5", "MEJEC" },
    { "E6", "Rockchip Electronics Co Ltd" },
    { "67", "Dongguan Guanma e-commerce Co Ltd" },
    { "68", "Rayson Hi-Tech (SZ) Limited" },
    { "E9", "MINRES Technologies GmbH" },
    { "EA", "Himax Technologies Inc" },
    { "6B", "Shenzhen Cwinner Technology Co Ltd" },
    { "EC", "Tecmiyo" },
    { "6D", "Shenzhen Suhuicun Technology Co Ltd" },
    { "6E", "Vickter Electronics Co. Ltd." },
    { "EF", "lowRISC" },
    { "70", "EXEGate FZE" },
    { "F1", "Shenzhen 9 Chapter Technologies Co" },
    { "F2", "Addlink" },
    { "73", "Starsway" },
    { "F4", "Pensando Systems Inc." },
    { "75", "AirDisk" },
    { "76", "Shenzhen Speedmobile Technology Co" },
    { "F7", "PEZY Computing" },
    { "F8", "Extreme Engineering Solutions Inc" },
    { "79", "Shangxin Technology Co Ltd" },
    { "7A", "Shanghai Zhaoxin Semiconductor Co" },
    { "FB", "Xsight Labs Ltd" },
    { "7C", "Hangzhou Hikstorage Technology Co" },
    { "FD", "Dell Technologies" },
    { "FE", "Guangdong StarFive Technology Co" },
};

// Continuation 13
std::unordered_map<std::string, std::string> bank14 {
    { "01", "TECOTON" },
    { "02", "Abko Co Ltd" },
    { "83", "Shenzhen Feisrike Technology Co Ltd" },
    { "04", "Shenzhen Sunhome Electronics Co Ltd" },
    { "85", "Global Mixed-mode Technology Inc" },
    { "86", "Shenzhen Weien Electronics Co. Ltd." },
    { "07", "Shenzhen Cooyes Technology Co Ltd" },
    { "08", "Keymos Electronics Co., Limited" },
    { "89", "E-Rockic Technology Company Limited" },
    { "8A", "Aerospace Science Memory Shenzhen" },
    { "0B", "Shenzhen Quanji Technology Co Ltd" },
    { "8C", "Dukosi" },
    { "0D", "Maxell Corporation of America" },
    { "0E", "Shenshen Xinxintao Electronics Co Ltd" },
    { "8F", "Zhuhai Sanxia Semiconductor Co Ltd" },
    { "10", "Groq Inc" },
    { "91", "AstraTek" },
    { "92", "Shenzhen Xinyuze Technology Co Ltd" },
    { "13", "All Bit Semiconductor" },
    { "94", "ACFlow" },
    { "15", "Shenzhen Sipeed Technology Co Ltd" },
    { "16", "Linzhi Hong Kong Co Limited" },
    { "97", "Supreme Wise Limited" },
    { "98", "Blue Cheetah Analog Design Inc" },
    { "19", "Hefei Laiku Technology Co Ltd" },
    { "1A", "Zord" },
    { "9B", "SBO Hearing A/S" },
    { "1C", "Regent Sharp International Limited" },
    { "9D", "Permanent Potential Limited" },
    { "9E", "Creative World International Limited" },
    { "1F", "Base Creation International Limited" },
    { "20", "Shenzhen Zhixin Chuanglian Technology" },
    { "A1", "Protected Logic Corporation" },
    { "A2", "Sabrent" },
    { "23", "Union Memory" },
    { "A4", "NEUCHIPS Corporation" },
    { "25", "Ingenic Semiconductor Co Ltd" },
    { "26", "SiPearl" },
    { "A7", "Shenzhen Actseno Information Technology" },
    { "A8", "RIVAI Technologies (Shenzhen) Co Ltd" },
    { "29", "Shenzhen Sunny Technology Co Ltd" },
    { "2A", "Cott Electronics Ltd" },
    { "AB", "Shanghai Synsense Technologies Co Ltd" },
    { "2C", "Shenzhen Jintang Fuming Optoelectronics" },
    { "AD", "CloudBEAR LLC" },
    { "AE", "Emzior, LLC" },
    { "2F", "Ehiway Microelectronic Science Tech Co" },
    { "B0", "UNIM Innovation Technology (Wu XI)" },
    { "31", "GDRAMARS" },
    { "32", "Meminsights Technology" },
    { "B3", "Zhuzhou Hongda Electronics Corp Ltd" },
    { "34", "Luminous Computing Inc" },
    { "B5", "PROXMEM" },
    { "B6", "Draper Labs" },
    { "37", "ORICO Technologies Co. Ltd." },
    { "38", "Space Exploration Technologies Corp" },
    { "B9", "AONDEVICES Inc" },
    { "BA", "Shenzhen Netforward Micro Electronic" },
    { "3B", "Syntacore Ltd" },
    { "BC", "Shenzhen Secmem Microelectronics Co" },
    { "3D", "ONiO As" },
    { "3E", "Shenzhen Peladn Technology Co Ltd" },
    { "BF", "O-Cubes Shanghai Microelectronics" },
    { "40", "ASTC" },
    { "C1", "UMIS" },
    { "C2", "Paradromics" },
    { "43", "Sinh Micro Co Ltd" },
    { "C4", "Metorage Semiconductor Technology Co" },
    { "45", "Aeva Inc" },
    { "46", "HongKong Hyunion Electronics Co Ltd" },
    { "C7", "China Flash Co Ltd" },
    { "C8", "Sunplus Technology Co Ltd" },
    { "49", "Idaho Scientific" },
    { "4A", "Suzhou SF Micro Electronics Co Ltd" },
    { "CB", "IMEX Cap AG" },
    { "4C", "Fitipower Integrated Technology Co Ltd" },
    { "CD", "ShenzhenWooacme Technology Co Ltd" },
    { "CE", "KeepData Original Chips" },
    { "4F", "Rivos Inc" },
    { "D0", "Big Innovation Company Limited" },
    { "51", "Wuhan YuXin Semiconductor Co Ltd" },
    { "52", "United Memory Technology (Jiangsu)" },
    { "D3", "PQShield Ltd" },
    { "54", "ArchiTek Corporation" },
    { "D5", "ShenZhen AZW Technology Co Ltd" },
    { "D6", "Hengchi Zhixin (Dongguan) Technology" },
    { "57", "Eggtronic Engineering Spa" },
    { "58", "Fusontai Technology" },
    { "D9", "PULP Platform" },
    { "DA", "Koitek Electronic Technology (Shenzhen) Co" },
    { "5B", "Shenzhen Jiteng Network Technology Co" },
    { "DC", "Aviva Links Inc" },
    { "5D", "Trilinear Technologies Inc" },
    { "5E", "Shenzhen Developer Microelectronics Co" },
    { "DF", "Guangdong OPPO Mobile Telecommunication" },
    { "E0", "Akeana" },
    { "61", "Lyczar" },
    { "62", "Shenzhen Qiji Technology Co Ltd" },
    { "E3", "Shenzhen Shangzhaoyuan Technology" },
    { "64", "Han Stor" },
    { "E5", "China Micro Semicon Co., Ltd." },
    { "E6", "Shenzhen Zhuqin Technology Co Ltd" },
    { "67", "Shanghai Ningyuan Electronic Technology" },
    { "68", "Auradine" },
    { "E9", "Suzhou Yishuo Electronics Co Ltd" },
    { "EA", "Faurecia Clarion Electronics" },
    { "6B", "SiMa Technologies" },
    { "EC", "CFD Sales Inc" },
    { "6D", "Suzhou Comay Information Co Ltd" },
    { "6E", "Yentek" },
    { "EF", "Qorvo Inc" },
    { "70", "Shenzhen Youzhi Computer Technology" },
    { "F1", "Sychw Technology (Shenzhen) Co Ltd" },
    { "F2", "MK Founder Technology Co Ltd" },
    { "73", "Siliconwaves Technologies Co Ltd" },
    { "F4", "Hongkong Hyunion Electronics Co Ltd" },
    { "75", "Shenzhen Xinxinzhitao Electronics Business" },
    { "76", "Shenzhen HenQi Electronic Commerce Co" },
    { "F7", "Shenzhen Jingyi Technology Co Ltd" },
    { "F8", "Xiaohua Semiconductor Co. Ltd." },
    { "79", "Shenzhen Dalu Semiconductor Technology" },
    { "7A", "Shenzhen Ninespeed Electronics Co Ltd" },
    { "FB", "ICYC Semiconductor Co Ltd" },
    { "7C", "Shenzhen Jaguar Microsystems Co Ltd" },
    { "FD", "Beijing EC-Founder Co Ltd" },
    { "FE", "Shenzhen Taike Industrial Automation Co" },
};

// Continuation 14
std::unordered_map<std::string, std::string> bank15 {
    { "01", "Kalray SA" },
    { "02", "Shanghai Iluvatar CoreX Semiconductor Co" },
    { "83", "Fungible Inc" },
    { "04", "Song Industria E Comercio de Eletronicos" },
    { "85", "DreamBig Semiconductor Inc" },
    { "86", "ChampTek Electronics Corp" },
    { "07", "Fusontai Technology" },
    { "08", "Endress Hauser AG" },
    { "89", "altec ComputerSysteme GmbH" },
    { "8A", "UltraRISC Technology (Shanghai) Co Ltd" },
    { "0B", "Shenzhen Jing Da Kang Technology Co Ltd" },
    { "8C", "Hangzhou Hongjun Microelectronics Co Ltd" },
    { "0D", "Pliops Ltd" },
    { "0E", "Cix Technology (Shanghai) Co Ltd" },
    { "8F", "TeraDevices Inc" },
    { "10", "SpacemiT (Hangzhou)Technology Co Ltd" },
    { "91", "InnoPhase loT Inc" },
    { "92", "InnoPhase loT Inc" },
    { "13", "Yunhight Microelectronics" },
    { "94", "Samnix" },
    { "15", "HKC Storage Co Ltd" },
    { "16", "Chiplego Technology (Shanghai) Co Ltd" },
    { "97", "StoreSkill" },
    { "98", "Shenzhen Astou Technology Company" },
    { "19", "Guangdong LeafFive Technology Limited" },
    { "1A", "Jin JuQuan" },
    { "9B", "Huaxuan Technology (Shenzhen) Co Ltd" },
    { "1C", "Gigastone Corporation" },
    { "9D", "Kinsotin" },
    { "9E", "PengYing" },
    { "1F", "Shenzhen Xunhi Technology Co Ltd" },
    { "20", "FOXX Storage Inc" },
    { "A1", "Shanghai Belling Corporation Ltd" },
    { "A2", "Glenfy Tech Co Ltd" },
    { "23", "Sahasra Semiconductors Pvt Ltd" },
    { "A4", "Chongqing SeekWave Technology Co Ltd" },
    { "25", "Shenzhen Zhixing Intelligent Manufacturing" },
    { "26", "Ethernovia" },
    { "A7", "Shenzhen Xinrongda Technology Co Ltd" },
    { "A8", "Hangzhou Clounix Technology Limited" },
    { "29", "JGINYUE" },
    { "2A", "Shenzhen Xinwei Semiconductor Co Ltd" },
    { "AB", "COLORFIRE Technology Co Ltd" },
    { "2C", "B LKE" },
    { "AD", "ZHUDIAN" },
    { "AE", "REECHO" },
    { "2F", "Enphase Energy Inc" },
    { "B0", "Shenzhen Yingrui Storage Technology Co Ltd" },
    { "31", "Shenzhen Sinomos Semiconductor Technology" },
    { "32", "O2micro International Limited" },
    { "B3", "Axelera AI BV" },
    { "34", "Silicon Legend Technology (Suzhou) Co Ltd" },
    { "B5", "Suzhou Novosense Microelectronics Co Ltd" },
    { "B6", "Pirateman" },
    { "37", "Yangtze MasonSemi" },
    { "38", "Shanghai Yunsilicon Technology Co Ltd" },
    { "B9", "Rayson" },
    { "BA", "Alphawave IP" },
    { "3B", "Shenzhen Visions Chip Electronic Technology" },
    { "BC", "KYO Group" },
    { "3D", "Shenzhen Aboison Technology Co Ltd" },
    { "3E", "Shenzhen JingSheng Semiconducto Co Ltd" },
    { "BF", "Shenzhen Dingsheng Technology Co Ltd" },
    { "40", "EVAS Intelligence Co Ltd" },
    { "C1", "Kaibright Electronic Technologies" },
};

std::unordered_map<std::string, std::string> banks[] {
    bank1, bank2, bank3, bank4, bank5, bank6, bank7, bank8,
    bank9, bank10, bank11, bank12, bank13, bank14, bank15
};

bool check_if_id_format(std::string vendor_id) {
    // Check if size is in 2 char chunks
    if (vendor_id.size() % 2)
        return false;

    // Check if value only has hex characters
    return vendor_id.find_first_not_of("0123456789abcdefABCDEF") == std::string::npos;
}

std::string convert_id_to_vendor(std::string vendor_id) {
    std::string two_hex_str;

    if (!check_if_id_format(vendor_id))
        return vendor_id;

    while (!vendor_id.empty()) {
        two_hex_str = vendor_id.substr(0, 2);
        vendor_id = vendor_id.substr(2);

        if (two_hex_str != CONTINUATION_CODE)
            break;
    }

    // Get bank number
    std::istringstream buffer(two_hex_str);
    uint16_t value;
    buffer >> std::hex >> value;

    // Remove parity bit
    value &= 0x7F;

    // Get vendor number
    two_hex_str = vendor_id.substr(0, 2);

    return banks[value][two_hex_str];
}

#endif // JEDEC_HPP_